---
# tasks file for ansible-role-example

- include_vars: "{{ ansible_os_family }}.yml"

- name: Include platform-specific tasks for installation
  include: "install-{{ ansible_os_family }}.yml"

- name: Include platform-specific tasks for configuration
  include: "configure-{{ ansible_os_family }}.yml"

# all common tasks should be here
